/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmanggota.java
 *
 * Created on Jan 1, 2006, 2:55:22 AM
 */

package form;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import kelas.Anggota;

/**
 *
 * @author Administrator
 */
public class frmanggota extends javax.swing.JDialog{
kelas.Anggota angg;
    public frmanggota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        angg = new Anggota();
        tbl_an.setModel(angg.modelAnggota);
        btn_jenisKel.setSelected(null, modal);
        angg.tampilData();
        btn_update.setVisible(false);
        setLocationRelativeTo(null);
        tampilId();
    }

    private void tampilId(){
        int row = tbl_an.getRowCount();
        int col = tbl_an.getColumnCount();
        if(row==0){
            txt_id_an.setText("AN-1");
        } else {
        Object[] val =new Object[col];
        for (int k = 0; k < val.length - 1; k++) {
            for (int i = 0; i < row; i++) {
                for (int j = 0; j <col; j++) {
                    val[k] = tbl_an.getValueAt(i, 0);
                    String id = val[k].toString();
                    int ambil = Integer.parseInt(id.substring(3, 4))+1;
                    txt_id_an.setText("AN-"+String.valueOf(ambil));
                    }
            }
            }
        }
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_jenisKel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_cari = new javax.swing.JTextField();
        lbl_cari_an = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_an = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbl_id_an = new javax.swing.JLabel();
        txt_id_an = new javax.swing.JTextField();
        txt_nama_an = new javax.swing.JTextField();
        lbl_nm_an = new javax.swing.JLabel();
        lbl_tmp_lhr_an = new javax.swing.JLabel();
        txt_tmpt_lhr_an = new javax.swing.JTextField();
        lbl_jns_kel_an = new javax.swing.JLabel();
        lbl_tgl_lhr_an = new javax.swing.JLabel();
        lbl_almt_an = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_almt_an = new javax.swing.JTextArea();
        txt_jenis_kel = new javax.swing.JTextField();
        opt_L = new javax.swing.JRadioButton();
        opt_P = new javax.swing.JRadioButton();
        opt_kerja = new javax.swing.JComboBox();
        txt_kerja = new javax.swing.JTextField();
        lbl_pkj_an = new javax.swing.JLabel();
        jLahir = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_baru = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        lbl_bk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ANGGOTA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 260, -1));

        lbl_cari_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_cari_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_cari_an.setText("PENCARIAN");
        jPanel1.add(lbl_cari_an, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        tbl_an.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_an.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_anMouseClicked(evt);
            }
        });
        tbl_an.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbl_anCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl_an);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 49, 500, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 530, 500));

        jPanel2.setOpaque(false);

        lbl_id_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_id_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_id_an.setText("No Anggota");

        txt_id_an.setEditable(false);
        txt_id_an.setNextFocusableComponent(txt_nama_an);
        txt_id_an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_anActionPerformed(evt);
            }
        });

        txt_nama_an.setNextFocusableComponent(txt_tmpt_lhr_an);
        txt_nama_an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_anActionPerformed(evt);
            }
        });

        lbl_nm_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_nm_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_nm_an.setText("Nama");

        lbl_tmp_lhr_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_tmp_lhr_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_tmp_lhr_an.setText("Tempat Lahir");

        lbl_jns_kel_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_jns_kel_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_jns_kel_an.setText("Jenis Kelamin");

        lbl_tgl_lhr_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_tgl_lhr_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_tgl_lhr_an.setText("Tanggal Lahir");

        lbl_almt_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_almt_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_almt_an.setText("Alamat");

        txt_almt_an.setColumns(20);
        txt_almt_an.setRows(5);
        txt_almt_an.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_almt_an.setNextFocusableComponent(opt_kerja);
        jScrollPane2.setViewportView(txt_almt_an);

        txt_jenis_kel.setEditable(false);
        txt_jenis_kel.setBorder(null);
        txt_jenis_kel.setOpaque(false);

        btn_jenisKel.add(opt_L);
        opt_L.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_L.setForeground(new java.awt.Color(51, 0, 153));
        opt_L.setText("L");
        opt_L.setContentAreaFilled(false);
        opt_L.setNextFocusableComponent(opt_P);
        opt_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_LActionPerformed(evt);
            }
        });

        btn_jenisKel.add(opt_P);
        opt_P.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_P.setForeground(new java.awt.Color(51, 0, 153));
        opt_P.setText("P");
        opt_P.setContentAreaFilled(false);
        opt_P.setNextFocusableComponent(lbl_almt_an);

        opt_kerja.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_kerja.setForeground(new java.awt.Color(51, 0, 153));
        opt_kerja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Disini -", "MAHASISWA", "PELAJAR", "UMUM", "- Lainnya -" }));
        opt_kerja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opt_kerja.setNextFocusableComponent(txt_kerja);
        opt_kerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_kerjaActionPerformed(evt);
            }
        });

        txt_kerja.setEditable(false);
        txt_kerja.setFont(new java.awt.Font("Tahoma", 1, 11));
        txt_kerja.setForeground(new java.awt.Color(51, 0, 153));
        txt_kerja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kerjaActionPerformed(evt);
            }
        });

        lbl_pkj_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_pkj_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_pkj_an.setText("Status");

        jLahir.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_id_an)
                        .addGap(37, 37, 37)
                        .addComponent(txt_id_an, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_nm_an)
                        .addGap(76, 76, 76)
                        .addComponent(txt_nama_an, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_jns_kel_an)
                        .addGap(28, 28, 28)
                        .addComponent(opt_L)
                        .addGap(26, 26, 26)
                        .addComponent(opt_P)
                        .addGap(26, 26, 26)
                        .addComponent(txt_jenis_kel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_almt_an)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_pkj_an)
                        .addGap(68, 68, 68)
                        .addComponent(opt_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txt_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tmp_lhr_an)
                            .addComponent(lbl_tgl_lhr_an))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tmpt_lhr_an, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_id_an))
                    .addComponent(txt_id_an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_nm_an))
                    .addComponent(txt_nama_an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_tmp_lhr_an))
                    .addComponent(txt_tmpt_lhr_an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_tgl_lhr_an)
                    .addComponent(jLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_jns_kel_an))
                    .addComponent(opt_L)
                    .addComponent(opt_P)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_jenis_kel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_almt_an)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pkj_an)
                    .addComponent(opt_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 420, 400));

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".:: FORM INPUT DATA ANGGOTA ::.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/label.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 940, 130));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kembali.png"))); // NOI18N
        btn_home.setBorder(null);
        btn_home.setContentAreaFilled(false);
        btn_home.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel4.add(btn_home);
        btn_home.setBounds(14, 5, 60, 60);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan2.png"))); // NOI18N
        btn_simpan.setBorder(null);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel4.add(btn_simpan);
        btn_simpan.setBounds(150, 5, 60, 60);

        btn_baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baru.png"))); // NOI18N
        btn_baru.setBorder(null);
        btn_baru.setContentAreaFilled(false);
        btn_baru.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        jPanel4.add(btn_baru);
        btn_baru.setBounds(79, 5, 60, 60);

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan2.png"))); // NOI18N
        btn_update.setBorder(null);
        btn_update.setContentAreaFilled(false);
        btn_update.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel4.add(btn_update);
        btn_update.setBounds(150, 5, 60, 60);

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hapus.png"))); // NOI18N
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel4.add(btn_hapus);
        btn_hapus.setBounds(220, 5, 60, 60);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 300, 70));

        lbl_bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_back.jpg"))); // NOI18N
        getContentPane().add(lbl_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_anMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_anMouseClicked
        // TODO add your handling code here:
       btn_simpan.setVisible(false);
       btn_update.setVisible(true);

       int row=tbl_an.getSelectedRow();
       String Id = tbl_an.getValueAt(row, 0).toString();
       String Nama=tbl_an.getValueAt(row, 1).toString();
       String TempatLahir=tbl_an.getValueAt(row, 2).toString();
       String TglLahir=tbl_an.getValueAt(row, 3).toString();
       String Jnskel=tbl_an.getValueAt(row, 4).toString();
       String Alamat=tbl_an.getValueAt(row, 5).toString();
       String Kerja=tbl_an.getValueAt(row, 6).toString();


    txt_id_an.setText(Id);
    txt_nama_an.setText(Nama);
    txt_tmpt_lhr_an.setText(TempatLahir);

        int iTahun = Integer.parseInt(TglLahir.substring(6,10));
        int iBulan = Integer.parseInt(TglLahir.substring(3,5))-1;
        int iTgl = Integer.parseInt(TglLahir.substring(0,2));

        Calendar cal = Calendar.getInstance();
        cal.set(iTahun,iBulan,iTgl);
        jLahir.setDate(cal.getTime());

    if (Jnskel.equalsIgnoreCase("Laki-Laki")){
        opt_L.setSelected(rootPaneCheckingEnabled);
    } else if (Jnskel.equalsIgnoreCase("Perempuan")){
        opt_P.setSelected(rootPaneCheckingEnabled);
    }
    txt_almt_an.setText(Alamat);
    txt_kerja.setText(Kerja);
    }//GEN-LAST:event_tbl_anMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        txt_jenis_kel.setVisible(false);

        String tampilan="yyyy-MM-dd";
        SimpleDateFormat df = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(df.format(jLahir.getDate()));

        if (opt_L.isSelected()){
           txt_jenis_kel.setText("Laki-Laki");
        }else if (opt_P.isSelected()){
           txt_jenis_kel.setText("Perempuan");
        }
            angg.insert(txt_id_an.getText(), txt_nama_an.getText(), txt_tmpt_lhr_an.getText(),
                tanggal, txt_jenis_kel.getText(),txt_almt_an.getText(),
                txt_kerja.getText());
            
           btn_baruActionPerformed(evt);
    
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tbl_anCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbl_anCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_anCaretPositionChanged

    private void txt_id_anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_anActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_id_anActionPerformed

    private void opt_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_LActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_opt_LActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
                dispose();
        //dashboard frm = new dashboard();
        //frm.setVisible(true);

    }//GEN-LAST:event_btn_homeActionPerformed

    private void opt_kerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_kerjaActionPerformed
        // TODO add your handling code here:
        String liskerja = opt_kerja.getSelectedItem().toString();
        if (opt_kerja.getSelectedIndex()==0){
            txt_kerja.setText("");
            txt_kerja.setEditable(false);
        } else if (opt_kerja.getSelectedIndex()<=3){
            txt_kerja.setText(liskerja);
        } else if (opt_kerja.getSelectedIndex()==4){
            txt_kerja.setText("");
            txt_kerja.setEditable(true);
        }
    }//GEN-LAST:event_opt_kerjaActionPerformed

    private void txt_kerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kerjaActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String tampilan="yyyy-MM-dd";
        SimpleDateFormat df = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(df.format(jLahir.getDate()));

        if (opt_L.isSelected()){
           txt_jenis_kel.setText("Laki-Laki");
        }else if (opt_P.isSelected()){
           txt_jenis_kel.setText("Perempuan");
        }

    int jawab = JOptionPane.showConfirmDialog(null, "Yakin Data Akan Diperbaharui?", "PERBAHARUI DATA", JOptionPane.YES_NO_OPTION);
    if(jawab == JOptionPane.YES_OPTION){
            angg.update(txt_id_an.getText(), txt_nama_an.getText(), txt_tmpt_lhr_an.getText(),
                tanggal, txt_jenis_kel.getText(),txt_almt_an.getText(),
                txt_kerja.getText());
                angg.tampilData();
                btn_baruActionPerformed(evt);
    } else if (jawab == JOptionPane.NO_OPTION){
            btn_baruActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        // TODO add your handling code here:
        angg.cari(txt_cari.getText());
    }//GEN-LAST:event_txt_cariCaretUpdate

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
    txt_nama_an.setText("");
    txt_tmpt_lhr_an.setText("");
    jLahir.setCalendar(null);
    btn_jenisKel.clearSelection();
    txt_jenis_kel.setText("");
    txt_almt_an.setText("");
    opt_kerja.setSelectedIndex(0);
    txt_kerja.setText("");
    txt_kerja.setEditable(false);
    angg.tampilData();
    btn_update.setVisible(false);
    btn_simpan.setVisible(true);
    tampilId();
    }//GEN-LAST:event_btn_baruActionPerformed

    private void txt_nama_anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_anActionPerformed

    }//GEN-LAST:event_txt_nama_anActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(null, "Yakin Akan Menghapus Data?", "HAPUS DATA", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION){
            angg.hapusdata(txt_id_an.getText());
            angg.tampilData();
            btn_baruActionPerformed(evt);
        } else if (jawab == JOptionPane.NO_OPTION){
    btn_baruActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateMouseClicked

    private void jDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateMouseEntered

    private void jDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDatePropertyChange

    private void jDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateCaretPositionChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmanggota dialog = new frmanggota(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_home;
    private javax.swing.ButtonGroup btn_jenisKel;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JDateChooser jLahir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_almt_an;
    private javax.swing.JLabel lbl_bk;
    private javax.swing.JLabel lbl_cari_an;
    private javax.swing.JLabel lbl_id_an;
    private javax.swing.JLabel lbl_jns_kel_an;
    private javax.swing.JLabel lbl_nm_an;
    private javax.swing.JLabel lbl_pkj_an;
    private javax.swing.JLabel lbl_tgl_lhr_an;
    private javax.swing.JLabel lbl_tmp_lhr_an;
    private javax.swing.JRadioButton opt_L;
    private javax.swing.JRadioButton opt_P;
    private javax.swing.JComboBox opt_kerja;
    private javax.swing.JTable tbl_an;
    private javax.swing.JTextArea txt_almt_an;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_an;
    private javax.swing.JTextField txt_jenis_kel;
    private javax.swing.JTextField txt_kerja;
    private javax.swing.JTextField txt_nama_an;
    private javax.swing.JTextField txt_tmpt_lhr_an;
    // End of variables declaration//GEN-END:variables

}
