 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmbuku.java
 *
 * Created on Jan 1, 2006, 2:55:45 AM
 */

package form;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class frmbuku extends javax.swing.JDialog {
kelas.Buku bk;
    /** Creates new form frmbuku */
    public frmbuku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bk = new kelas.Buku();
        tbl_buku.setModel(bk.modelBuku);
        btn_update.setVisible(false);
        setLocationRelativeTo(null);
        bk.tampilData();
        tampilId();
    }
    private void tampilId(){
       int row = tbl_buku.getRowCount();
        int col = tbl_buku.getColumnCount();
        if(row==0){
            txt_id_buku.setText("BK-1");
        } else {
        Object[] val =new Object[col];
        for (int k = 0; k < val.length - 1; k++) {
            for (int i = 0; i < row; i++) {
                for (int j = 0; j <col; j++) {
                    val[k] = tbl_buku.getValueAt(i, 0);
                    String id = val[k].toString();
                    int ambil = Integer.parseInt(id.substring(3, 4))+1;
                    txt_id_buku.setText("BK-"+String.valueOf(ambil));
                    }
            }
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_id_an = new javax.swing.JLabel();
        txt_id_buku = new javax.swing.JTextField();
        txt_kat = new javax.swing.JTextField();
        lbl_nm_an = new javax.swing.JLabel();
        lbl_tmp_lhr_an = new javax.swing.JLabel();
        txt_judul = new javax.swing.JTextField();
        lbl_jns_kel_an = new javax.swing.JLabel();
        lbl_tgl_lhr_an = new javax.swing.JLabel();
        lbl_almt_an = new javax.swing.JLabel();
        opt_sumber = new javax.swing.JComboBox();
        lbl_pkj_an = new javax.swing.JLabel();
        txt_pengarang = new javax.swing.JTextField();
        txt_penerbit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_jum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        opt_tahun = new javax.swing.JComboBox();
        opt_penerbit = new javax.swing.JComboBox();
        txt_tahun = new javax.swing.JTextField();
        opt_juml = new javax.swing.JComboBox();
        txt_sumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        opt_kat = new javax.swing.JComboBox();
        txt_no = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_cari = new javax.swing.JTextField();
        lbl_cari_an = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_buku = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_baru = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        lbl_bk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BUKU");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        lbl_id_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_id_an.setForeground(new java.awt.Color(50, 0, 153));
        lbl_id_an.setText("Kode Buku");

        txt_id_buku.setEditable(false);

        txt_kat.setEditable(false);
        txt_kat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_katActionPerformed(evt);
            }
        });

        lbl_nm_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_nm_an.setForeground(new java.awt.Color(50, 0, 153));
        lbl_nm_an.setText("No Buku");

        lbl_tmp_lhr_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_tmp_lhr_an.setForeground(new java.awt.Color(50, 0, 153));
        lbl_tmp_lhr_an.setText("Judul Buku");

        txt_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_judulActionPerformed(evt);
            }
        });

        lbl_jns_kel_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_jns_kel_an.setForeground(new java.awt.Color(50, 0, 153));
        lbl_jns_kel_an.setText("Penerbit");

        lbl_tgl_lhr_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_tgl_lhr_an.setForeground(new java.awt.Color(50, 0, 153));
        lbl_tgl_lhr_an.setText("Pengarang");

        lbl_almt_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_almt_an.setForeground(new java.awt.Color(50, 0, 153));
        lbl_almt_an.setText("Tahun Terbit");

        opt_sumber.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_sumber.setForeground(new java.awt.Color(50, 0, 153));
        opt_sumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Disini -", "HADIAH", "PEMBELIAN", "SUMBANGAN", "- Lainnya -" }));
        opt_sumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_sumberActionPerformed(evt);
            }
        });

        lbl_pkj_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_pkj_an.setForeground(new java.awt.Color(50, 0, 153));
        lbl_pkj_an.setText("Sumber");

        txt_pengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pengarangActionPerformed(evt);
            }
        });

        txt_penerbit.setEditable(false);
        txt_penerbit.setFont(new java.awt.Font("Tahoma", 1, 11));
        txt_penerbit.setForeground(new java.awt.Color(50, 0, 153));
        txt_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_penerbitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(50, 0, 153));
        jLabel2.setText("Jumlah Buku");

        txt_jum.setEditable(false);
        txt_jum.setFont(new java.awt.Font("Tahoma", 1, 11));
        txt_jum.setForeground(new java.awt.Color(50, 0, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(50, 0, 153));
        jLabel4.setText("Buku");

        opt_tahun.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_tahun.setForeground(new java.awt.Color(50, 0, 153));
        opt_tahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Disini -", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "- Lainnya -" }));
        opt_tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_tahunActionPerformed(evt);
            }
        });

        opt_penerbit.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_penerbit.setForeground(new java.awt.Color(50, 0, 153));
        opt_penerbit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Disini -", "ANDI", "Diva Press", "Elex Media", "Eurika", "Gagas Media", "Gerai Pop", "Grafindo", "Komputindo", "M&C!", "Majalah Anak", "Mizan", "MQ Gress", "MQS Publishing", "PT. Gramedia", "PT. Informatika", "Puspa Swara", "Redaksi", "Republika", "Ronny Saputra", "Trubus", "Walt Disney", "- Lainnya -" }));
        opt_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_penerbitActionPerformed(evt);
            }
        });

        txt_tahun.setEditable(false);
        txt_tahun.setFont(new java.awt.Font("Tahoma", 1, 11));
        txt_tahun.setForeground(new java.awt.Color(50, 0, 153));

        opt_juml.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_juml.setForeground(new java.awt.Color(50, 0, 153));
        opt_juml.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Disini -", "1", "2", "3", "4", "5", "- Lainnya -" }));
        opt_juml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_jumlActionPerformed(evt);
            }
        });

        txt_sumber.setEditable(false);
        txt_sumber.setFont(new java.awt.Font("Tahoma", 1, 11));
        txt_sumber.setForeground(new java.awt.Color(50, 0, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(50, 0, 153));
        jLabel5.setText("Kategori");

        opt_kat.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_kat.setForeground(new java.awt.Color(50, 0, 153));
        opt_kat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Disini -", "FIKSI A", "FIKSI B", "FIKSI C", "FIKSI D", "FIKSI E", "UMUM A", "UMUM B", "UMUM C", "UMUM D", "UMUM E" }));
        opt_kat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_katActionPerformed(evt);
            }
        });

        txt_no.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_noInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tmp_lhr_an)
                    .addComponent(lbl_tgl_lhr_an)
                    .addComponent(lbl_jns_kel_an)
                    .addComponent(lbl_almt_an)
                    .addComponent(jLabel2)
                    .addComponent(lbl_pkj_an)
                    .addComponent(lbl_nm_an)
                    .addComponent(lbl_id_an)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(opt_kat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(txt_kat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_id_buku, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txt_no, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txt_pengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(opt_sumber, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opt_juml, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opt_penerbit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opt_tahun, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sumber, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txt_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txt_tahun, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_jum, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(1, 1, 1))
                    .addComponent(txt_judul, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id_an)
                    .addComponent(txt_id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(opt_kat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_kat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nm_an))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tmp_lhr_an)
                    .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tgl_lhr_an)
                    .addComponent(txt_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jns_kel_an)
                    .addComponent(opt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_almt_an)
                    .addComponent(opt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txt_jum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opt_juml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt_sumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pkj_an)
                    .addComponent(txt_sumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 400, 380));

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".:: FORM INPUT DATA BUKU ::.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/label.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 930, 130));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 260, -1));

        lbl_cari_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_cari_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_cari_an.setText("PENCARIAN");
        jPanel1.add(lbl_cari_an, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        tbl_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_buku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 490, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 520, 520));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kembali.png"))); // NOI18N
        btn_home.setBorder(null);
        btn_home.setContentAreaFilled(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel4.add(btn_home);
        btn_home.setBounds(4, 11, 61, 55);

        btn_baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baru.png"))); // NOI18N
        btn_baru.setBorder(null);
        btn_baru.setContentAreaFilled(false);
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        jPanel4.add(btn_baru);
        btn_baru.setBounds(70, 10, 61, 55);

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan2.png"))); // NOI18N
        btn_update.setBorder(null);
        btn_update.setContentAreaFilled(false);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel4.add(btn_update);
        btn_update.setBounds(140, 10, 61, 55);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan2.png"))); // NOI18N
        btn_simpan.setBorder(null);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel4.add(btn_simpan);
        btn_simpan.setBounds(140, 10, 61, 55);

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hapus.png"))); // NOI18N
        btn_hapus.setBorder(null);
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel4.add(btn_hapus);
        btn_hapus.setBounds(210, 10, 59, 55);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 280, 70));

        lbl_bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_back.jpg"))); // NOI18N
        getContentPane().add(lbl_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pengarangActionPerformed

    private void txt_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_penerbitActionPerformed

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        // TODO add your handling code here:
        bk.cari(txt_cari.getText());
        //bk.tampilData();
}//GEN-LAST:event_txt_cariCaretUpdate

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        //dashboard frm = new dashboard();
        //frm.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        bk.insert(txt_id_buku.getText(), txt_kat.getText(), txt_no.getText(), txt_judul.getText(), txt_pengarang.getText(), txt_penerbit.getText(), txt_tahun.getText(), txt_jum.getText(), txt_sumber.getText());
        btn_baruActionPerformed(evt);
}//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(null, "Yakin Data Akan Diperbaharui?", "PERBAHARUI DATA", JOptionPane.YES_NO_OPTION);
        if(jawab == JOptionPane.YES_OPTION){
            bk.update(txt_id_buku.getText(), txt_kat.getText(), txt_no.getText(),txt_judul.getText(),
                txt_pengarang.getText(), txt_penerbit.getText(),txt_tahun.getText(),
                txt_jum.getText(), txt_sumber.getText());
                bk.tampilData();
                btn_baruActionPerformed(evt);
        } else {
        btn_baruActionPerformed(evt);
        }
}//GEN-LAST:event_btn_updateActionPerformed

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        bk.tampilData();
        tampilId();
        opt_kat.setSelectedIndex(0);
        txt_kat.setText("");
        txt_no.setText("");
        txt_judul.setText("");
        txt_pengarang.setText("");
        opt_penerbit.setSelectedIndex(0);
        txt_penerbit.setText("");
        opt_tahun.setSelectedIndex(0);
        txt_tahun.setText("");
        opt_juml.setSelectedIndex(0);
        txt_jum.setText("");
        opt_sumber.setSelectedIndex(0);
        txt_sumber.setText("");
        btn_update.setVisible(false);
        btn_simpan.setVisible(true);
}//GEN-LAST:event_btn_baruActionPerformed

    private void opt_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_penerbitActionPerformed
        // TODO add your handling code here:
        String listpenerbit=opt_penerbit.getSelectedItem().toString();

                    if (opt_penerbit.getSelectedIndex()==0){
                        txt_penerbit.setText("");
                        txt_penerbit.setEditable(false);
                    }else if (opt_penerbit.getSelectedIndex()<=21){
                        txt_penerbit.setText(listpenerbit);
                    }else if(opt_penerbit.getSelectedIndex()==22){
                        txt_penerbit.setText("");
                        txt_penerbit.setEditable(true);
                    }
    }//GEN-LAST:event_opt_penerbitActionPerformed

    private void opt_tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_tahunActionPerformed
        // TODO add your handling code here:
        String listtahun=opt_tahun.getSelectedItem().toString();

                    if (opt_tahun.getSelectedIndex()==0){
                        txt_tahun.setText("");
                        txt_tahun.setEditable(false);
                    }else if (opt_tahun.getSelectedIndex()<=71){
                        txt_tahun.setText(listtahun);
                    }else if(opt_tahun.getSelectedIndex()==72){
                        txt_tahun.setText("");
                        txt_tahun.setEditable(true);
                    }
    }//GEN-LAST:event_opt_tahunActionPerformed

    private void opt_jumlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_jumlActionPerformed
        // TODO add your handling code here:
         String listjumlah=opt_juml.getSelectedItem().toString();

                    if (opt_juml.getSelectedIndex()==0){
                        txt_jum.setText("");
                        txt_jum.setEditable(false);
                    }else if (opt_juml.getSelectedIndex()<=5){
                        txt_jum.setText(listjumlah);
                    }else if(opt_juml.getSelectedIndex()==6){
                        txt_jum.setText("");
                        txt_jum.setEditable(true);
                    }
    }//GEN-LAST:event_opt_jumlActionPerformed

    private void opt_sumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_sumberActionPerformed
        // TODO add your handling code here:
        String listsumber=opt_sumber.getSelectedItem().toString();

                    if (opt_sumber.getSelectedIndex()==0){
                        txt_sumber.setText("");
                        txt_sumber.setEditable(false);
                    }else if (opt_sumber.getSelectedIndex()<=3){
                        txt_sumber.setText(listsumber);
                    }else if(opt_sumber.getSelectedIndex()==4){
                        txt_sumber.setText("");
                        txt_sumber.setEditable(true);
                    }
    }//GEN-LAST:event_opt_sumberActionPerformed

    private void opt_katActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_katActionPerformed
        // TODO add your handling code here
        String listKat = opt_kat.getSelectedItem().toString();
        if(opt_kat.getSelectedIndex()==0){
            txt_kat.setEditable(false);
        } else if (opt_kat.getSelectedIndex()!=0){
            txt_kat.setText(listKat);

        }
    }//GEN-LAST:event_opt_katActionPerformed

    private void txt_katActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_katActionPerformed
        // TODO add your handling code here:
        //String show="";
        String kategori =opt_kat.getSelectedItem().toString();
        String no = txt_kat.getText();
        //show = kategori+no;
    }//GEN-LAST:event_txt_katActionPerformed

    private void txt_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_judulActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_judulActionPerformed

    private void txt_noInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_noInputMethodTextChanged

    }//GEN-LAST:event_txt_noInputMethodTextChanged

    private void tbl_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bukuMouseClicked
        // TODO add your handling code here:
        btn_simpan.setVisible(false);
        btn_update.setVisible(true);
        
         int row = tbl_buku.getSelectedRow();
         String Id = tbl_buku.getValueAt(row, 0).toString();
         String Kat = tbl_buku.getValueAt(row, 1).toString();
         String No = tbl_buku.getValueAt(row, 2).toString();
         String Judul = tbl_buku.getValueAt(row, 3).toString();
         String Pengarang = tbl_buku.getValueAt(row, 4).toString();
         String Penerbit = tbl_buku.getValueAt(row, 5).toString();
         String Tahun = tbl_buku.getValueAt(row, 6).toString();
         String Jumlah = tbl_buku.getValueAt(row, 7).toString();
         String Sumber = tbl_buku.getValueAt(row, 8).toString();

        txt_id_buku.setText(Id);
        txt_kat.setText(Kat);
        txt_no.setText(No);
        txt_judul.setText(Judul);
        txt_pengarang.setText(Pengarang);
        txt_penerbit.setText(Penerbit);
        txt_tahun.setText(Tahun);
        txt_jum.setText(Jumlah);
        txt_sumber.setText(Sumber);
        bk.tampilData();
    }//GEN-LAST:event_tbl_bukuMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(null, "Yakin Akan Menghapus Data?", "HAPUS DATA", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION){
            bk.hapusdata(txt_id_buku.getText());
            bk.tampilData();
            btn_baruActionPerformed(evt);
        } else if (jawab == JOptionPane.NO_OPTION){
    btn_baruActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmbuku dialog = new frmbuku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_almt_an;
    private javax.swing.JLabel lbl_bk;
    private javax.swing.JLabel lbl_cari_an;
    private javax.swing.JLabel lbl_id_an;
    private javax.swing.JLabel lbl_jns_kel_an;
    private javax.swing.JLabel lbl_nm_an;
    private javax.swing.JLabel lbl_pkj_an;
    private javax.swing.JLabel lbl_tgl_lhr_an;
    private javax.swing.JLabel lbl_tmp_lhr_an;
    private javax.swing.JComboBox opt_juml;
    private javax.swing.JComboBox opt_kat;
    private javax.swing.JComboBox opt_penerbit;
    private javax.swing.JComboBox opt_sumber;
    private javax.swing.JComboBox opt_tahun;
    private javax.swing.JTable tbl_buku;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_buku;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_jum;
    private javax.swing.JTextField txt_kat;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_sumber;
    private javax.swing.JTextField txt_tahun;
    // End of variables declaration//GEN-END:variables

}
